### PR TITLE
fix(brand-icons): ensure ids are unique

### LINKED ISSUE #226: Multiple brand icons on page causes duplicate ID attribute issue
Each brand icon SVG has an inner element with `id="lg-icon-fill-primary"`. I believe this is used to apply the various brand colours, however having multiple icons on the page will cause issues due to the IDs not being unique.

Steps to reproduce:

1. Include 2 or more brand icons on a single page
2. Open Axe dev tool extension and test page
3. Notice the issue "id attribute value must be unique" is flagged

### PR DESCRIPTION
**Pull request by aaronBery**
# Description

Ensures ids in brand icons are unique to comply with accessibility requirements

Fixes #226

## Requirements

The change can be validated on the brand icons component page using the Axe Dev Tools extension (in Chrome) which should no longer flag 'id attribute value must be unique'

Storybook link: https://deploy-preview-247--legal-and-general-canopy.netlify.app/?path=/story/components-brand-icon--standard
Screenshot: 

Screenshot 2021-03-09 at 12 21 18

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)
- [x] I have provided an adequate amount of test coverage
- [ ] I have added the functionality to the [test app](./blob/master/docs/CONTRIBUTING.md#build-test-application)
- [ ] I have provided a story in storybook to document the changes
- [ ] I have provided documentation in the notes section of the story
- [ ] I have added any new public feature modules to public-api.ts
- [ ] I have [linked the new component](<(https://github.com/Legal-and-General/canopy/blob/master/docs/CONTRIBUTING.md#invision-dsm)>) to adobe DSM (if appropriate)

### CODE REVIEW

File: projects/canopy/src/lib/brand-icon/brand-icon.component.ts [hunk 1]
```diff
@@ -76,9 +76,18 @@ export class LgBrandIconComponent {
...
+    let idCount = 0;
+    let xlinkCount = 0;
+
     return svgData
-      .replace(/id="\w+"/g, () => `id="lg-brand-icon-${this.id}"`)
-      .replace(/xlink:href="#\w+"/g, () => `xlink:href="#lg-brand-icon-${this.id}"`);
+      .replace(/id="([^"]+)"/g, () => {
+        idCount++;
+        return `id="lg-brand-icon-${this.id}-${idCount}"`;
+      })
```
Comment (andy-polhill) [inline projects/canopy/src/lib/brand-icon/brand-icon.component.ts:86]:
```suggestion
      .replace(/id="([^"]+)"/g, () =>
        `id="lg-brand-icon-${this.id}-${idCount++}"`)
```
It's style only but you could do this (if readability is still ok?)

**Review by andy-polhill — APPROVED** [review]
Good fix, cheers @aaronBery 👍

**Review by paul-request — DISMISSED** [review]

File: projects/canopy/src/lib/brand-icon/brand-icon.component.spec.ts [hunk 2]
```diff
@@ -57,7 +57,11 @@ describe('LgBrandIconComponent', () => {
       fixture.detectChanges();
 
       expect(fixture.nativeElement.querySelector('#test')).toBeNull();
-      expect(fixture.nativeElement.querySelector('#lg-brand-icon-0')).toBeDefined();
+      expect(
+        /lg-brand-icon-\d-\d/.test(
```
Comment (aaronBery) [inline projects/canopy/src/lib/brand-icon/brand-icon.component.spec.ts:61]: i've updated this to match the pattern of the id that is set to ensure ids are unique. this is related to the bug #248 . I had attempted to access the nextUniqueId to reset it in the afterEach hook but it doesn't appear to be technically global. Asserting the id has this pattern does however provide value in confirming the replace has occurred

File: projects/canopy/src/lib/brand-icon/brand-icon.component.ts (hunk 1 above)
Comment (aaronBery) [reply projects/canopy/src/lib/brand-icon/brand-icon.component.ts]: yeah that's a bit slicker. made that change

**Review by paul-request — APPROVED** [review]
